###Obtener productos tienda
GET http://localhost:3000/tienda/productos


###Obtener saldo tienda
GET http://localhost:3000/tienda/saldo


















### 
PUT http://localhost:3000/tienda/productos
content-Type: application/json

{
"messages": [
{
"senderID": "60c4f100aaaa0a33e4e27ebd", "text": "dinamike guay", "receiverID": "60c4f116aaaa0a33e4e27ebe"
}, {

"senderID": "60c4f100aaaa0a33e4e27ebd", "text": "pero que quiero el JSON", "receiverID": "60c4f116aaaa0a33e4e27ebe"
}
]
}






###
DELETE http://localhost:3000/tienda/users/:id









### 
POST http://localhost:3000/tienda/productos
content-Type: application/json
{
"nombre": "Atún", "valor": 2
}








### 
POST http://localhost:3000/tienda/lots 
content-Type: application/json

{
"name": "yogur", "dimensions": "60x30x15", "weight": 60, "qty": 30, "price": 6, "isFragile": true, "info": "otro5", "minimumQty": 40, "businessItem": "60a900e05be6b70a807f5f3e", "userItem":"60c4fca0488f893984a0f410"
}






### 
PUT http://localhost:3000/tienda/lots/60a161814c1c6a41446e1034 
content-Type: application/json

{
"name": "Leche", "dimensions": "60x30x15", "weight": 60, "userItem": "6091cbdf81612f2a801c068f", "qty": 40, "price": 150, "isFragile": true, "info": "HA CAMBIADO OU YEAH", "minimumQty": 40, "businessItem": "60aeaf411ffb7307940ae113"
}

